name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push
        run: |
          docker build -t us-central1-docker.pkg.dev/doculoom-446020/vault-service/vault-service:latest .
          docker push us-central1-docker.pkg.dev/doculoom-446020/vault-service/vault-service:latest

      #@todo: not a best practice to deploy latest tag
      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy vault-service \
            --image "us-central1-docker.pkg.dev/doculoom-446020/vault-service/vault-service:latest" \
            --region "us-central1" \
            --platform "managed" \
            --allow-unauthenticated \
